### ISSUE TITLE
compiling plugin

### ISSUE THREAD

**Issue by reejinbouk** [emqtt/emq_auth_mysql#17]
Hello
i'm compiling this plugin
but when i run 'make tests' its throw this:

Updating /home/roman/emqttd/etc/emqttd_auth_mysql-master/emqttd-relx/_rel/emqttd/emqttd_auth_mysql/logs/index.html... done
Updating /home/roman/emqttd/etc/emqttd_auth_mysql-master/emqttd-relx/_rel/emqttd/emqttd_auth_mysql/logs/all_runs.html... done

erlang.mk:2168: ошибка выполнения рецепта для цели «ct»
make: *** [ct] Error 1

how can i compile it?

**Comment by huangdan** [comment]
the 'make test' command  common test. if you compile it,
Please download https://github.com/emqtt/emqttd-relx.git
